/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
 * Generated on: 01-Dec-2017 15:16:16
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 2
 * Denominator Length  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h 
 */
const int NL = 2;
const real64_T NUM[2] = {
     0.9960975909694,  -0.9960975909694
};
const int DL = 2;
const real64_T DEN[2] = {
                   1,  -0.9921951819388
};
