function Hd = filter45low
%FILTER45LOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 18-Nov-2017 14:58:12

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 512;  % Sampling Frequency

N    = 20;       % Order
Fc   = 45;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
